### PR TITLE
add CaseInsensitiveValues param to ParserSettings

### PR DESCRIPTION
**Pull request by regme**
for parsing enum values in caseInsensetive way

### CODE REVIEW

**Comment by nemec** [comment]
Looks great. Only comment: Can you change the name of the setting to `CaseInsensitiveEnumValues`? I don't want to mislead users into thinking that `-u https://google.com/ABC` is the same as `-u https://google.com/abc` (string/Uri value) with that setting turned on.

**Comment by regme** [comment]
All done! :+1: 
Thank you for your comment!

**Comment by nemec** [comment]
Can you also add one test case (with 3-4 `InlineData` points) for the parser where the value is True? Feel free to use [this test case](https://github.com/gsscoder/commandline/blob/33ef667f625b6c19c3872ab295e421bb25f43f43/tests/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L248) as a starting point.

**Comment by regme** [comment]
Added some tests :+1: 

✔ Parse_enum_value_ignore_case(arguments: ["--colors", "0"], expected: Red)
✔ Parse_enum_value_ignore_case(arguments: ["--colors", "1"], expected: Green)
✔ Parse_enum_value_ignore_case(arguments: ["--colors", "2"], expected: Blue)
✔ Parse_enum_value_ignore_case(arguments: ["--colors", "blue"], expected: Blue)
✔ Parse_enum_value_ignore_case(arguments: ["--colors", "green"], expected: Green)
✔ Parse_enum_value_ignore_case(arguments: ["--colors", "red"], expected: Red)

**Comment by mizipzor** [comment]
This is an awesome pull request. Textbook! I would have merged this myself but since @nemec provided the initial feedback, I leave it to him. Good work. :)

**Comment by nemec** [comment]
Perfect! Thanks for contributing to the project @regme

**Pull request merged**
