### PR TITLE
Tokenization of short options could produce strange behaviors

### PR DESCRIPTION
**Pull request by Thilas**
@gsscoder, if you have something like `git commit -mmymessage`, you expect to set the value `mymessage` to options `m`. Instead of that, you get (with this example) a `RepeatedOptionError`.
What I have done in my commit is, when tokenizing a short name, to continue yielding `Token.Name` while finding existing boolean options (and of course, I assume the first char is an option). As soon as I find a char that expects a value other than a boolean, then I assume the rest if the expected value. And as soon as I find a char that is not an existing option, I assume this char and the following is a value.
It changes slightly the existing logic, but it seems better to me (and don't break existing unit tests of course). Of course, I added new unit tests to reproduce this case (both in verb scenario and not).
What do you think?

### CODE REVIEW

**Comment by gsscoder** [comment]
@Thilas, first of all, thanks for PR.

If this doesn't break tests, I think that it conforms to `getopt()` parsing rules, can you confirm it?

Due to Issue #218, I've changed things in Tokenizer.cs and Token.cs, so this PR has now conflicts.

Can you re-align it to current codebase?

Thanks.

**Comment by Thilas** [comment]
@gsscoder, I did additional research on this topic and here are the results:

* according to §5 of http://pubs.opengroup.org/onlinepubs/7908799/xbd/utilconv.html#tag_009_001, only short options "that do not take option-arguments" can be grouped
* according to http://search.cpan.org/~cjm/Getopt-Mixed-1.10/lib/Getopt/Mixed.pm#DESCRIPTION:

> Short options which do not take an argument can be grouped together. Short options which do take an argument must be the last option in their group, because everything following the option will be considered to be its argument."

* according to http://perldoc.perl.org/Getopt/Long.html#Bundling, an other way is even mentioned: support of something like `-h24w80` but I think it can wait for a next version... :smile:

As a conclusion, I really think too this change conforms to `getopt()` parsing rules.

Anyway, conflicts are now resolved!

cc/ @nemec @mizipzor @gimmemoore

**Comment by gsscoder** [comment]
@Thilas, yes, this is how I tried to implement both this and previous version...

And if not perfectly compliant it must be! :+1:

**Comment by gsscoder** [comment]
@Thilas, do you have a Twitter account?

**Comment by gsscoder** [comment]
@Thilas, I've thanked you on Twitter: https://twitter.com/gsscoder/status/629146804194557952.

**Comment by Thilas** [comment]
@gsscoder, no I don't have any Twitter account but thank you for your message there :smiley:. And again thank you for your great work (and reactivity!) on this library!

**Comment by gsscoder** [comment]
@Thilas, I can count on very smart contributors! :smile:

**Pull request merged**
