### PR TITLE
Allows negative decimal numbers as values

### PR DESCRIPTION
**Pull request by tbroust-trepia**
If you provided "-2.5" as a parameter value, the library was basically considering it wasn't a value, but another parameter. This fixes it.

### CODE REVIEW

**Comment by gsscoder** [comment]
For the moment I can write a unit test about it. Thanks you, @tbroust-trepia.

**Comment by gsscoder** [comment]
This cases are covered. Some examples:
https://github.com/gsscoder/commandline/blob/master/src/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L43

https://github.com/gsscoder/commandline/blob/master/src/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L62

https://github.com/gsscoder/commandline/blob/master/src/CommandLine.Tests/Unit/Core/InstanceBuilderTests.cs#L88

To name few...

I'm talking of master branch, version 2.0.x-x.

**Comment by mizipzor** [comment]
Unless @tbroust-trepia is working on a new pull request i think this one should be left alone and replaced with a separate bug report in a new issue.

**Comment by gsscoder** [comment]
OK, the point is that current 2.0 codebase (at moment of writing this post) lacks that defect! :+1:

**Pull request closed without merging**
