### PR TITLE
Basic support for help text from resource files

### PR DESCRIPTION
**Pull request by balticer**
Hi,

pull request for #276  .

regards
Kai

### CODE REVIEW

**Comment by nemec** [comment]
FYI there are a number of existing tests that failed due to these changes: "Both HelpText and ResourceName cannot set at the same time". You can see full details in the appveyor link above.
If you can fix that and add a few tests with resource files I'll merge. I assume you can manually set the locale to test specific foreign localizations on, say, a US English PC?

**Comment by balticer** [comment]
Hey,

sorry for closing and reopen. I just deleted my dev branch and forgot about the open pull request based on the dev branch.

I've fixed a bug regarding to this feature in this commit: https://github.com/balticer/commandline/commit/e9fa316ae6d5ac5ac479f2728913fceaddfb1030

Regarding the failing tests:
The problem is that these tests not set _helpText_ nor _resourceName_. So when the behaviour is fine and of these **must** be set, then these tests have to be adjusted. I'm not insane with the testing project, but i'll look into.

regards
Kai

**Comment by nemec** [comment]
I see. However, HelpText is _not_ a required property so it doesn't make sense to throw an exception when no help text is present. To preserve backwards compatibility, we should return null when it hasn't been set.

**Comment by balticer** [comment]
AppVeyor build fails because of some problems with the build system. Locally it compiles fine, also the tests runnning fine. Any hint to fix the problem with the AppVeyor build system?

**Comment by nemec** [comment]
Have the `paket.lock` or `paket.dependencies` files changed locally? It sounds like you've added a dependency that isn't accounted for in the files that exist in source control.

**Comment by balticer** [comment]
No changes on this files locally. The AppVeyor build fails, not my local build. Possible to run AppVeyor again on this changeset?

**Comment by nemec** [comment]
When you build are you using `build.cmd` or the usual VS compile + test runner?

**Comment by ericnewton76** [comment]
Did this get merged?  I ask because I just got a email notification that said that 276 was closed, which is referenced on this PR

**Pull request closed without merging**
