### PR TITLE
Please - Tell people it's dead

### PR DESCRIPTION
**Pull request by timabell**
it's a waste of eveyone's time having an abandoned project that is still so
prominent

If you accept no other pull requests, please accept this one or update your
readme and nuget project yourself.

I lost several hours on this today.

Thanks for the code.

### CODE REVIEW

**Comment by cosmo0** [comment]
It's not so much that the project itself is dead, but that the owner has vanished.

I accept pull requests over my fork, if you're interested (but I don't develop on it).

**Comment by timabell** [comment]
Thanks I saw that and am using your fork. Unfortunately this original repo and nuget package is still highly visible. I guess this is the future of bit-rot.

**Comment by timabell** [comment]
By the way @cosmo0 you have 4 outstanding pull requests on your fork, perhaps you could take a look at them?

**Comment by cosmo0** [comment]
You're right ! Thanks.

**Comment by gsscoder** [comment]
I think I've apologized sufficiently for being away so long, so I'll not repeat my self.

This announcement explains why: https://github.com/gsscoder/commandline/issues/152 and says, as you can see from recent project activity, that is not dead.

Thanks everyone for patience...

**Pull request closed without merging**
