### PR TITLE
Added support for defining options in interfaces

### PR DESCRIPTION
**Pull request by smbecker**
For complex command line interfaces, it can be quite common for verbs to share a common set of options. This pull request allows for defining those options in base classes or interfaces so that the parameter names and help text values can be defined in one place for all verbs that share those options.

### CODE REVIEW

**Comment by gsscoder** [comment]
Makes sense. I go to work on this right now...

**Comment by gsscoder** [comment]
Thanks @smbecker, I delay this PR merge for the moment. I need to reason on it...
I'd like to hear more opinions,  if possible.

Just one thing: the main difference with previous stable is that 2.0 tries to use a _functional paradigm_ in coding as more as possible.

Can you rethink the change to `src/CommandLine/Core/ReflectionExtensions.cs` using **idiomatic Linq**?

Anyway, thank you for pointing out the question!

**Comment by smbecker** [comment]
Better?

**Comment by gsscoder** [comment]
@smbecker,
absolutely better! Thank you. The fault is mine, I've to update the contrib guidelines (for now a little outdated txt on doc folder) and put it in wiki. I think that @mizipzor can help in this...

OK,
ASAP I'll check it locally and I'll tell you.

For now thank you for contributing to this project!

**Comment by gsscoder** [comment]
@smbecker, thank you, merged!

**Pull request merged**
