### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mizipzor**
Tried to split up the work into multiple commits to categorize it somewhat. All of this is based on ReSharpers static code analysis. Some warnings remain however.

In the unit tests all the methods are named **Like_this_with_underscore** which goes against the convention in the rest of the project where methods are **NamedInPascal**. The obvious reason for renaming the test methods is to cut down on the warnings improving signal to noise ratio, making other and new warnings stand out more. But naming appears deliberate so I didn't change it, I wanted to discuss it first.

 The other thing is a code block that's kinda repeated in a few places that look like this:
```
        public override bool Equals(object obj)
        {
            var other = obj as Token;
            if (other != null)
            {
                return Equals(other);
            }

            return base.Equals(obj);
        }
```
ReSharper says *"Call to 'base.Equals(...)' is reference equality"*, I'm not sure what it means, do you? 

Then we have a few cases where there currently is a reference comparison but we probably want a value comparison instead. Three of them in ```SentenceBuilder.cs```, first on line 90:
```return errMisssing.NameInfo == NameInfo.EmptyName```
Should be:
```return Equals(errMisssing.NameInfo, NameInfo.EmptyName)```
Do you agree?

I know I have write access to this repo but I decided to use a pull request so this can be discussed, I will also probably append a few more commits here.

### CODE REVIEW

**Comment by gsscoder** [comment]
@mizipzor, it's everything perfect! Thank you... But I ask you to revert back "Removed two return values not used etc...".
This was intentional and adhere to FP style.

As for immutable collection, e.g., the add method don't change the instance but returns you a new modified instance.
Sometime I've used this also when not _really_ necessary, but also to chain methods as here:
https://github.com/gsscoder/commandline/blob/master/src/CommandLine/Core/InstanceBuilder.cs#L83.

Ping me when this little thing is done and I'll merge the PR.

**Comment by gsscoder** [comment]
I've made an important fix for issue #172... Let me know if I can merge to master or if it's better wait you made the small change requested to your PR.

Thank you.

**Comment by mizipzor** [comment]
I'll revert the two return value changes, no problem.

Any thoughts on renaming the unit test methods from *Something_like_this* to *SomethingLikeThis*? Or if not, find an alternative approach to cut down on the ReSharper naming convention warnings?

**Comment by gsscoder** [comment]
OK, thanks with everything, @mizipzor!

About test naming: I like the first one (`That_style_for_being_clear`). For example in **F#** I would use quoting to allow spaces in method name. I'll never use such style outside test code, but for it I think is more understandable.

(About test code I was thinking about removing comments inside test methods: they originated in `InstanceBuilderTests` as a result of creating new methods by copy).

Perfect, I'll proceed with merge. :+1: 

Thank you again.

**Comment by mizipzor** [comment]
Hm, in that case I think we should try to find another way to hide the warnings. I assume you use ReSharper? Try in Visual Studio to go to *ReSharper -> Inspect -> Code issues in solution*. We currently have 27 issues in the *Constraints Violations* category, all of them pointing out inconsistent names. 

Do you see my concern here that if we allow those to remain the 28th issue will be hard to spot, it's hidden by the others. Going from no issues to one issue is a much starker contrast and that's what I want.

ReSharper is listed on the projects front page, it is almost to be expected that using its static code analysis should return nothing, don't you think? ;)

**Comment by gsscoder** [comment]
> I assume you use ReSharper?

Yes, JetBrains provided a specific open source license for the project; but I use it also in ordinary work.

> ReSharper is listed on the projects front page, it is almost to be expected that using its static code analysis should return nothing, don't you think? ;)

This is true, hence not immediate priority due to **pre-release** status... But this is correct, we should comply R# rules ourself define!

Is not possible to define such rule only for `CommandLine.Tests` project? And if not, I'd like anyway to merge code clean-ups... Can we do this and find a solution continuing the discussion?

**Comment by mizipzor** [comment]
There we go, one rebase later and one commit less. Since history was rewritten one commit got a new hash, so if you already pulled this locally doublecheck.

**Comment by gsscoder** [comment]
@mizipzor, I've examined your PR using GitHub. Since I've find in this first review the little thing I'm asking you to change, I've not fetched the PR in a dev branch (as I always do before merge).

Yes, if possible. I'll ask you to resend the PR without the alterations in discussion.

As a side note, an important part of `Core/ValueMapper.cs` is changed with my last commits...

**Comment by mizipzor** [comment]
Hm, I'm afraid I'm not sure what you mean. Did I misunderstand what you want removed? Is it still in the code? 

Either way, I've rebased my changes on top of your master.

**Comment by gsscoder** [comment]
I simply mean that the first thing I do before merging is reviewing a PR using GitHub web site. Then I fetch it in a separate branch for further examination and if everything is OK, I merge to master...

Since I've detected since from GitHub review a little thing to change, I've asked you to resend the PR without that changes.

OK, I proceed...

**Comment by gsscoder** [comment]
E.g., since from GitHub check everything is OK I now executed:
```bash
$ git fetch origin pull/171/head:pr171
$ git checkout pr171
```
Then if the second check passes, I'll merge to master and push...

Probably there's a smarter way (?): it seems that you know git a lot better than me. I'm open to suggestions...

**Comment by gsscoder** [comment]
Some change, have broke a good number of tests. Can you please check it?
I've two suspects:
- xUnit issue of changing string[] -> IEnumerable<string> for some `[Theory]`
- or maybe some lambda was simplified but actually changed in meaning

If you've issues running tests from Visual Studio (I had in past), you can do it from console:
```PowerShell
PS P:\CommandLine> .\packages\xunit.runner.console.2.0.0\tools\xunit.console .\build\test\CommandLine.Tests.dll
xUnit.net console test runner (64-bit .NET 4.0.30319.18408)
Copyright (C) 2015 Outercurve Foundation.

Discovering: CommandLine.Tests
Discovered:  CommandLine.Tests
Starting:    CommandLine.Tests
Finished:    CommandLine.Tests

=== TEST EXECUTION SUMMARY ===
   CommandLine.Tests  Total: 126, Errors: 0, Failed: 0, Skipped: 0, Time: 2,396s
```

**Comment by mizipzor** [comment]
Regarding the pull, yes, that's absolutely the way to do it. You fetch my changes and look at the resulting code on your machine. However, for actually merging, making those commits end up in your repository, I would use the *Merge pull request* button here on this page. Especially now that the changes have been rebased on top of your master. If you want to check out these changes again do note that I rewrote history, so you should strip my branch:

```git checkout pr171
git reset --hard HEAD~5```

And then pull again.

Regarding the tests. Ops. Here I thought that the changes were in style only and had no functional effects. Rookie mistake. I'll have a look.

**Comment by gsscoder** [comment]
Mmm... For the moment I think that I stay with may git workflow, I don't fee confident with `reset --hard`! :)

> Rookie mistake. I'll have a look.

No problem...

Since this PR is in a private local branch, after you've made your changes, I can discard this and start again with the new you'll send. Right?

I wait your news! :+1:

**Comment by mizipzor** [comment]
Went back and reverted the changes in the test file, all test now passes. 

Also, I didn't have the xunit runner, it was easy to fix manually through NuGet but I do not know why it wasn't downloaded automatically. And my CommandLine.Tests.dll wasn't in build but rather in the default location, bin\Debug in the project folder.

History was changed, so scrap your local branch and re-fetch.

**Comment by gsscoder** [comment]
Yes, my fault, @mizipzor: `CommandLine.Tests.dll` is in `repo\build\test" after **FAKE** build script terminate.
I'll proceed!

**Comment by gsscoder** [comment]
Thanks, finally also branch 2.0 codebase looks more clean and we can keep it clean using the updated R# config.

cc/ @nemec @gimmemoore

**Pull request merged**
