### PR TITLE
Generate ParserResultExtensions dynamically

### PR DESCRIPTION
**Pull request by Thilas**
@gsscoder, here is a PR to generate ParserResultExtensions dynamically using a T4 text template. I also fix some xml documentation issues on this class.
Let me know what you think of that.

### CODE REVIEW

**Comment by gsscoder** [comment]
@Thilas, thanks for your work and for a second way of doing things. It's interesting.

Sincerely I don't think, signature of these extension methods will change so much to motivate the use of a template.

But this is a personal preference, I'm not (or better no more) a lover of code generation.

For now I would leave it unchanged.

**Comment by gsscoder** [comment]
@Thilas, to be honest, I'm planning to replace specific ParserResult<T> with this more general implementation Result<T1,T2> (https://github.com/gsscoder/railwaysharp/blob/master/src/RailwaySharp/ErrorHandling.cs).

Please give it a look...

:)

**Comment by Thilas** [comment]
@gsscoder, thanks for your feedback. Your generalization of ParserResult seems interesting. I'll have a closer look at it this weekend.

**Comment by gsscoder** [comment]
@Thilas, wonderful! But I've just ported the F# from [this project](https://github.com/fsprojects/Chessie).

The interesting thing is that as single C# source file, anyone can set a reference with Paket.

**Pull request closed without merging**
