### PR TITLE
Add support for dashdash in unparser for issue #254.

### PR DESCRIPTION
**Pull request by scadorel**
This PR fix issue #254.

### CODE REVIEW

**Comment by gsscoder** [comment]
@scadorel, thanks a lot for your contribution! :smile:

Very appreciated. :+1:

**Comment by gsscoder** [comment]
@scadorel, I don't know if you're on twitter or if you're in it, what's your account.... Anyway I've thanked you here (without properly linking you if you're in): https://twitter.com/gsscoder/status/654914927015149568 (as always I do with contrib., when possible).

**Comment by scadorel** [comment]
Thank you a lot :+1: 
I do not have a Twitter account yet.

**Comment by gsscoder** [comment]
@scadorel, no problem! just to let you know I appreciate your work.

PS (_uninportant blah blah_):
My digital social interactions occur on Twitter, around GitHub projects (which I maintain, reporting issues on others etc) and obviously via e-mails. It's an enourmous piece of day-time and sometime "ordinary" job forces me stay away from these things from a while. :(
**(Recently I taken habit to try warn people using a GitHub isse marked as _announcement_ and post it to Twitter --- e.g. my latest a. near to decay is #250 --- in case I can predict that my presence will be reduced for job duties).**

:paperclip: As software developer I'm fascinated from Facebook (their infrastructure is incredible!) and I'm very interested in some projects they opensourced here on GitHub. Years ago I've tried to keep a personal account open, but I found my self spending too much time in it (to avoid offend people with missing reply or with missing "like" etc); at the end of the story (for me) FB is a great to let unknown people know about you and let your friends misunderstood you. So I ended cleaning it's content and deleting the account. I've done it a pair of times and now I'm good with **Twitter+GitHub+EMail** that's the _maximum_ the _(digital)_ social part of my brain can handle! :smile:

**Comment by scadorel** [comment]
Agreed on what you said. :+1: 
I finally created a Twitter account to give it a try :)
https://twitter.com/sebcadorel

**Pull request merged**
